orbs:
  github-cli: circleci/github-cli@2.7.0

version: 2.1

parameters:
  go-version:
    type: string
    default: "1.23"

executors:
  go-executor:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>

jobs:
  verify:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install Task
          command: |
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /tmp
            sudo mv /tmp/task /usr/local/bin/
      - run:
          name: Build
          command: go build ./...
      - run:
          name: Test with JUnit output
          command: task test-junit
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - run:
          name: Verify formatting
          command: |
            if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
              gofmt -s -l .
              echo "Code is not formatted. Please run 'gofmt -s -w .'"
              exit 1
            fi

  build-platform:
    parameters:
      goos:
        type: string
      goarch:
        type: string
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install Task
          command: |
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /tmp
            sudo mv /tmp/task /usr/local/bin/
      - run:
          name: Create build directory
          command: mkdir -p bin
      - run:
          name: Build for << parameters.goos >>/<< parameters.goarch >>
          command: |
            # Set binary extension based on OS
            if [ "<< parameters.goos >>" = "windows" ]; then
              BINARY_EXT=".exe"
            else
              BINARY_EXT=""
            fi
            GOOS=<< parameters.goos >> GOARCH=<< parameters.goarch >> GO_BINARY_EXT=${BINARY_EXT} task build
      - run:
          name: List built binaries
          command: ls -la bin
      - persist_to_workspace:
          root: .
          paths:
            - bin

  collect-artifacts:
    executor: go-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: List all binaries
          command: ls -la bin
      - store_artifacts:
          path: bin
          destination: binaries

  publish-github-release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - github-cli/setup
      - run:
          name: Publish GitHub Release
          command: |
            if [ -z "<< pipeline.git.tag >>" ]; then
              SHORT_HASH=$(echo "<< pipeline.git.revision >>" | cut -c1-7)
              TAG="0.0.0-${SHORT_HASH}"
            else
              TAG="<< pipeline.git.tag >>"
            fi

            # Create more informative release notes
            BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            PIPELINE_URL="https://app.circleci.com/pipelines/github/circleci-petri/rule-tool/<< pipeline.number >>"

            cat > release_notes.md << EOF
            # Automated release from CircleCI

            **Build Information:**
            - Build Date: ${BUILD_DATE}
            - CircleCI Pipeline: [#<< pipeline.number >>](${PIPELINE_URL})
            - Branch: << pipeline.git.branch >>
            - Commit: << pipeline.git.revision >>
            EOF

            # Add note about tag if it exists
            if [ -n "<< pipeline.git.tag >>" ]; then
              echo "- Tag: << pipeline.git.tag >>" >> release_notes.md
            fi

            gh release create "$TAG" ./bin/* --title "$TAG" --notes-file release_notes.md

workflows:
  build-all-platforms:
    jobs:
      - verify
      - build-platform:
          requires:
            - verify
          matrix:
            parameters:
              goos: ["linux", "darwin", "windows"]
              goarch: ["amd64", "arm64"]
            exclude:
              - goos: "windows"
                goarch: "arm64"
      - collect-artifacts:
          requires:
            - build-platform
      - publish-github-release:
          context: rule-tool-trunk
          requires:
            - collect-artifacts
          filters:
            branches:
              only: trunk
